export const TYPES = {
    ILogger: Symbol.for('ILogger'),
    IUserRepository: Symbol.for('IUserRepository'),
    IEmailService: Symbol.for('IEmailService'),
    IPasswordService: Symbol.for('IPasswordService'),
    IIdGeneratingService: Symbol.for('IIdGeneratingService'),
    ISystemConfigService: Symbol.for('ISystemConfigService'),
    IPaymentGatewayService: Symbol.for('IPaymentGatewayService'),
    IOtpService: Symbol.for('IOtpService'),
    IRegisterUseCase: Symbol.for('IRegisterUseCase'),
    EmailQueue: Symbol.for('EmailQueue'),
    PrismaClient: Symbol.for('PrismaClient'),
    AuthController: Symbol.for('AuthController'),
    Argon2Service: Symbol.for('Argon2Service'),
    IOtpRepository: Symbol.for('IOtpRepository'),
    ISendVerificationCodeUsecase: Symbol.for('ISendVerificationCodeUsecase'),
    IVerifyCredentialsUseCase: Symbol.for('IVerifyCredentialsUseCase'),
    ITokenGeneratorService: Symbol.for('ITokenGeneratorService'),
    ILoginUseCase: Symbol.for('ILoginUseCase'),
    IGetUserUsecase: Symbol.for('IGetUserUsecase'),
    IGoogleAuthUsecase: Symbol.for('IGoogleAuthUsecase'),
    ICompleteProfileUsecase: Symbol.for('ICompleteProfileUsecase'),
    IForgotPasswordUsecase: Symbol.for('IForgotPasswordUsecase'),
    IChangePasswordUsecase: Symbol.for('IChangePasswordUsecase'),
    AuthenticateMiddleware: Symbol.for('AuthenticateMiddleware'),
    AuthorizeMiddleware: Symbol.for('AuthorizeMiddleware'),
    UserController: Symbol.for('UserController'),
    ISendProfileChangePasswordOtpUsecase: Symbol.for(
        'ISendProfileChangePasswordOtpUsecase',
    ),
    IChangeProfilePasswordUsecase: Symbol.for('IChangeProfilePasswordUsecase'),
    IEditprofileSendOtpUsecase: Symbol.for('IEditprofileSendOtpUsecase'),
    IEditProfileUsecase: Symbol.for('IEditProfileUsecase'),
    ISendOtpUsecase: Symbol.for('ISendOtpUsecase'),
    OtpPolicyService: Symbol.for('OtpPolicyService'),
    IStorageService: Symbol.for('IStorageService'),
    S3Client: Symbol.for('S3Client'),
    IGenerateAvatarUploadUrlUsecase: Symbol.for(
        'IGenerateAvatarUploadUrlUsecase',
    ),
    IUpdateAvatarUrlUsecase: Symbol.for('IUpdateAvatarUrlUsecase'),
    IGetUserHomeStatsUsecase: Symbol.for('IGetUserHomeStatsUsecase'),
    IGetKycUploadUrlUsecase: Symbol.for('IGetKycUploadUrlUsecase'),
    KycController: Symbol.for('KycController'),
    IKycRepository: Symbol.for('IKycRepository'),
    IGetKycStatusUsecase: Symbol.for('IGetKycStatusUsecase'),
    IKycDocumentRepository: Symbol.for('IKycDocumentRepository'),
    IUpdateKycUsecase: Symbol.for('IUpdateKycUsecase'),
    ISubmitKycUsecase: Symbol.for('ISubmitKycUsecase'),
    IGetAllUsersUseCase: Symbol.for('IGetAllUsersUseCase'),
    AdminController: Symbol.for('AdminController'),
    AdminRoutes: Symbol.for('AdminRoutes'),
    IBlockUserUsecase: Symbol.for('IBlockUserUsecase'),
    IGetAdminUserUsecase: Symbol.for('IGetAdminUserUsecase'),
    IGetAllSellersUsecase: Symbol.for('IGetAllSellersUsecase'),
    IGetAdminDashboardStatsUsecase: Symbol.for(
        'IGetAdminDashboardStatsUsecase',
    ),
    IGetAdminSellerUsecase: Symbol.for('IGetAdminSellerUsecase'),
    IApproveSellerKycUsecase: Symbol.for('IApproveSellerKycUsecase'),
    IRejectSellerKycUsecase: Symbol.for('IRejectSellerKycUsecase'),
    IAuctionRepository: Symbol.for('IAuctionRepository'),
    ICreateAuctionUsecase: Symbol.for('ICreateAuctionUsecase'),
    IGetSellerAuctionsUsecase: Symbol.for('IGetSellerAuctionsUsecase'),
    IGetAuctionByIdUsecase: Symbol.for('IGetAuctionByIdUsecase'),
    IGenerateAuctionUploadUrlUsecase: Symbol.for(
        'IGenerateAuctionUploadUrlUsecase',
    ),
    IUpdateAuctionUsecase: Symbol.for('IUpdateAuctionUsecase'),
    IGetBrowseAuctionsUsecase: Symbol.for('IGetBrowseAuctionsUsecase'),
    IGetUserHomeAuctionFeedUsecase: Symbol.for(
        'IGetUserHomeAuctionFeedUsecase',
    ),
    IGetUserParticipatedAuctionsUsecase: Symbol.for(
        'IGetUserParticipatedAuctionsUsecase',
    ),
    IPublishAuctionUsecase: Symbol.for('IPublishAuctionUsecase'),
    IEndAuctionUsecase: Symbol.for('IEndAuctionUsecase'),
    AuctionController: Symbol.for('AuctionController'),
    AuctionRoutes: Symbol.for('AuctionRoutes'),
    IBidRepository: Symbol.for('IBidRepository'),
    IAuctionParticipantRepository: Symbol.for('IAuctionParticipantRepository'),
    IPlaceBidUsecase: Symbol.for('IPlaceBidUsecase'),
    IGetAuctionRoomUsecase: Symbol.for('IGetAuctionRoomUsecase'),
    IPauseAuctionUsecase: Symbol.for('IPauseAuctionUsecase'),
    IResumeAuctionUsecase: Symbol.for('IResumeAuctionUsecase'),
    ICreateAuctionCategoryUsecase: Symbol.for('ICreateAuctionCategoryUsecase'),
    IAuctionChatMessageRepository: Symbol.for('IAuctionChatMessageRepository'),
    ISendAuctionChatMessageUsecase: Symbol.for(
        'ISendAuctionChatMessageUsecase',
    ),
    IGetAuctionChatMessagesUsecase: Symbol.for(
        'IGetAuctionChatMessagesUsecase',
    ),
    IAuctionCategoryRepository: Symbol.for('IAuctionCategoryRepositoy'),
    IRequestAuctionCategoryUsecase: Symbol.for(
        'IRequestAuctionCategoryUsecase',
    ),
    ISlugGeneratorService: Symbol.for('ISlugGeneratorService'),
    IGetAllAuctionCategoriesUsecase: Symbol.for(
        'IGetAllAuctionCategoriesUsecase',
    ),
    IGetAllCategoryRequestUsecase: Symbol.for('IGetAllCategoryRequestUsecase'),
    IApproveAuctionCategoryUsecase: Symbol.for(
        'IApproveAuctionCategoryUsecase',
    ),
    IChangeAuctionCategoryStatusUsecase: Symbol.for(
        'IChangeAuctionCategoryStatusUsecase',
    ),
    IGetAllAdminAuctionCategoriesUsecase: Symbol.for(
        'IGetAllAdminAuctionCategoriesUsecase',
    ),
    IGetAdminAuctionsUsecase: Symbol.for('IGetAdminAuctionsUsecase'),
    IUpdateAuctionCategoryUsecase: Symbol.for('IUpdateAuctionCategoryUsecase'),
    IGetSystemConfigsUsecase: Symbol.for('IGetSystemConfigsUsecase'),
    IGetSystemConfigKeysUsecase: Symbol.for('IGetSystemConfigKeysUsecase'),
    ICreateSystemConfigUsecase: Symbol.for('ICreateSystemConfigUsecase'),
    IEditSystemConfigUsecase: Symbol.for('IEditSystemConfigUsecase'),
    ISystemConfigRepository: Symbol.for('ISystemConfigRepository'),
    ICreateSubscriptionPlanUsecase: Symbol.for(
        'ICreateSubscriptionPlanUsecase',
    ),
    IUpdateSubscriptionPlanStatusUsecase: Symbol.for(
        'IUpdateSubscriptionPlanStatusUsecase',
    ),
    IGetSubscriptionPlansUsecase: Symbol.for('IGetSubscriptionPlansUsecase'),
    IGetSubscribedUsersUsecase: Symbol.for('IGetSubscribedUsersUsecase'),
    IGetSubscriptionFeaturesUsecase: Symbol.for(
        'IGetSubscriptionFeaturesUsecase',
    ),
    ISubscriptionPlanRepository: Symbol.for('ISubscriptionPlanRepository'),
    IUserSubscriptionRepository: Symbol.for('IUserSubscriptionRepository'),
    IRazorpaySubscriptionGatewayService: Symbol.for(
        'IRazorpaySubscriptionGatewayService',
    ),
    IGetPublicSubscriptionPlansUsecase: Symbol.for(
        'IGetPublicSubscriptionPlansUsecase',
    ),
    IStartUserSubscriptionCheckoutUsecase: Symbol.for(
        'IStartUserSubscriptionCheckoutUsecase',
    ),
    IViewKycUsecase: Symbol.for('IViewKycUsecase'),
    IGetAllSellerAuctionCategoryRequestUsecase: Symbol.for(
        'IGetAllSellerAuctionCategoryRequestUsecase',
    ),
    SellerController: Symbol.for('SellerController'),
    IGetSellerAuctionPaymentsUsecase: Symbol.for(
        'IGetSellerAuctionPaymentsUsecase',
    ),
    IRejectAuctionCategoryUsecase: Symbol.for('IRejectAuctionCategoryUsecase'),
    IGetAllSellerAuctionsUsecase: Symbol.for('IGetAllSellerAuctionsUsecase'),
    IGetSellerDashboardStatsUsecase: Symbol.for(
        'IGetSellerDashboardStatsUsecase',
    ),
    Redis: Symbol.for('Redis'),
    IBidLockService: Symbol.for('IBidLockService'),
    ISocketServer: Symbol.for('ISocketServer'),
    ISocketClient: Symbol.for('ISocketClient'),
    ISocketContainer: Symbol.for('ISocketContainer'),
    IEncryptionService: Symbol.for('IEncryptionService'),
    PlaceLongAuctionBidStrategy: Symbol.for('PlaceLongAuctionBidStrategy'),
    PlaceSealedAuctionBidStrategy: Symbol.for('PlaceSealedAuctionBidStrategy'),
    LongAuctionWinnerStrategy: Symbol.for('LongAuctionWinnerStrategy'),
    SealedAuctionWinnerStrategy: Symbol.for('SealedAuctionWinnerStrategy'),
    PlaceBidPolicyService: Symbol.for('PlaceBidPolicyService'),
    AuctionWinnerPolicyFactory: Symbol.for('AuctionWinnerPolicyFactory'),
    AuctionWinnerPolicyService: Symbol.for('AuctionWinnerPolicyService'),
    INotificationRepository: Symbol.for('INotificationRepository'),
    IGetUserNotificationsUsecase: Symbol.for('IGetUserNotificationsUsecase'),
    IWalletRepository: Symbol.for('IWalletRepository'),
    IGetOrCreateWalletUsecase: Symbol.for('IGetOrCreateWalletUsecase'),
    IEventBus: Symbol.for('IEventBus'),
    OnAuctionEndHandler: Symbol.for('OnAuctionEndHandler'),
    OnNotificationCreatedHandler: Symbol.for('OnNotificationCreatedHandler'),
    IWalletTransactionsRepository: Symbol.for('IWalletTransactionsRepository'),
    ICreditWalletUsecase: Symbol.for('ICreditWalletUsecase'),
    IDebitWalletUsecase: Symbol.for('IDebitWalletUsecase'),
    ICreateWalletTopupSessionUsecase: Symbol.for(
        'ICreateWalletTopupSessionUsecase',
    ),
    IConfirmWalletTopupUsecase: Symbol.for('IConfirmWalletTopupUsecase'),
    WalletController: Symbol.for('WalletController'),
    WebhookController: Symbol.for('WebhookController'),
    IPaymentRepository: Symbol.for('IPaymentRepository'),
    IAuctionPaymentAmountSplitStrategy: Symbol.for(
        'IAuctionPaymentAmountSplitStrategy',
    ),
    ICreatePendingPaymentForAuctionUsecase: Symbol.for(
        'ICreatePendingPaymentForAuctionUsecase',
    ),
    IProcessAuctionEndAfterCloseUsecase: Symbol.for(
        'IProcessAuctionEndAfterCloseUsecase',
    ),
    IAuctionEndQueue: Symbol.for('IAuctionEndQueue'),
    IGetUserPaymentsUsecase: Symbol.for('IGetUserPaymentsUsecase'),
    ICreatePaymentOrderUsecase: Symbol.for('ICreatePaymentOrderUsecase'),
    IVerifyPaymentUsecase: Symbol.for('IVerifyPaymentUsecase'),
    IDeclinePaymentUsecase: Symbol.for('IDeclinePaymentUsecase'),
    IAuctionBidLeaderboardService: Symbol.for('IAuctionBidLeaderboardService'),
    IAuctionWinnerFallbackQueue: Symbol.for('IAuctionWinnerFallbackQueue'),
    IProcessAuctionWinnerFallbackUsecase: Symbol.for(
        'IProcessAuctionWinnerFallbackUsecase',
    ),
    IGetFallBackAuctionWinnerStrategy: Symbol.for(
        'IGetFallBackAuctionWinnerStrategy',
    ),
    PaymentsController: Symbol.for('PaymentsController'),
    LongAuctionCreatePolicy: Symbol.for('LongAuctionCreatePolicy'),
    SealedAuctionCreatePolicy: Symbol.for('SealedAuctionCreatePolicy'),
    AuctionCreatePolicyFactory: Symbol.for('AuctionCreatePolicyFactory'),
    PlaceBidStartegyFactory: Symbol.for('PlaceBidStartegyFactory'),
    IAutoBidService: Symbol.for('IAutoBidService'),
    IAutoBidConfigRepository: Symbol.for('IAutoBidConfigRepository'),
    ICreateAutoBidConfigUsecase: Symbol.for('ICreateAutoBidConfigUsecase'),
    IUpdateAutoBidConfigUsecase: Symbol.for('IUpdateAutoBidConfigUsecase'),
    IDisableAutoBidConfigUsecase: Symbol.for('IDisableAutoBidConfigUsecase'),
    IGetUserAutoBidConfigUsecase: Symbol.for('IGetUserAutoBidConfigUsecase'),
    LongAuctionPlaceBidStrategy: Symbol.for('LongAuctionPlaceBidStrategy'),
    SealedAuctionPlaceBidStartegy: Symbol.for('SealedAuctionPlaceBidStartegy'),
    AuctionWinnerStrategyFactory: Symbol.for('AuctionWinnerStrategyFactory'),
    IProcessAuctionEndNotificationUsecase: Symbol.for(
        'IProcessAuctionEndNotificationUsecase',
    ),
    IAuctionPaymentsStrategy: Symbol.for('IAuctionPaymentsStrategy'),
    IAuctionWinnerRepository: Symbol.for('IAuctionWinnerRepository'),
    IFailAuctionUsecase: Symbol.for('IFailAuctionUsecase'),
    ISendPublicFallbackPublicNotificationUsecase: Symbol.for(
        'ISendPublicFallbackPublicNotificationUsecase',
    ),
    IProcessFallbackPublicNotificationUsecase: Symbol.for(
        'IProcessFallbackPublicNotificationUsecase',
    ),
    IFallbackPublicNotificationQueue: Symbol.for(
        'IFallbackPublicNotificationQueue',
    ),
    IFallbackAuctionParticipantsRepo: Symbol.for(
        'IFallbackAuctionParticipantsRepo',
    ),
    IFallbackAuctionRepository: Symbol.for('IFallbackAuctionRepository'),
    ICreatePaymentOrderForPublicFallbackAuctionUsecase: Symbol.for(
        'ICreatePaymentOrderForPublicFallbackAuctionUsecase',
    ),
    IVerifyFallbackPublicAuctionPaymentUsecase: Symbol.for(
        'IVerifyFallbackPublicAuctionPaymentUsecase',
    ),
    IDeclinePublicFallbackAuctionUsecase: Symbol.for(
        'IDeclinePublicFallbackAuctionUsecase',
    ),
    IAddAuctionParticipantUsecase: Symbol.for('IAddAuctionParticipantUsecase'),
    IReleaseParticipantsWalletUsecase: Symbol.for(
        'IReleaseParticipantsWalletUsecase',
    ),
    AuctionParticipantMapper: Symbol.for('AuctionParticipantMapper'),
    AuctionCategoryMapper: Symbol.for('AuctionCategoryMapper'),
    AuctionChatMessageMapper: Symbol.for('AuctionChatMessageMapper'),
    AuctionWinnerMapper: Symbol.for('AuctionWinnerMapper'),
    AuctionMapper: Symbol.for('AuctionMapper'),
    BidMapper: Symbol.for('BidMapper'),
    FallbackAuctionParticipantsMapper: Symbol.for(
        'FallbackAuctionParticipantsMapper',
    ),
    FallbackPublicAuctionMapper: Symbol.for('FallbackPublicAuctionMapper'),
    KycDocumentMapper: Symbol.for('KycDocumentMapper'),
    KycMapper: Symbol.for('KycMapper'),
    NotificationMapper: Symbol.for('NotificationMapper'),
    OtpMapper: Symbol.for('OtpMapper'),
    PaymentsMapper: Symbol.for('PaymentsMapper'),
    WalletMapper: Symbol.for('WalletMapper'),
    UserMapper: Symbol.for('UserMapper'),
    WalletTransactionMapper: Symbol.for('WalletTransactionMapper'),
    SystemConfigMapper: Symbol.for('SystemConfigMapper'),
    SubscriptionPlanMapper: Symbol.for('SubscriptionPlanMapper'),
    UserSubscriptionMapper: Symbol.for('UserSubscriptionMapper'),
    LiveAuctionCreatePolicy: Symbol.for('LiveAuctionCreatePolicy'),
    IFraudReportRepository: Symbol.for('IFraudReportRepository'),
    IUserSuspensionRepository: Symbol.for('IUserSuspensionRepository'),
    ICreateFraudReportUsecase: Symbol.for('ICreateFraudReportUsecase'),
    IGetFraudReportsUsecase: Symbol.for('IGetFraudReportsUsecase'),
    IReviewFraudReportUsecase: Symbol.for('IReviewFraudReportUsecase'),
    IMarkFraudReportUnderReviewUsecase: Symbol.for(
        'IMarkFraudReportUnderReviewUsecase',
    ),
    IUpdateFraudReportUsecase: Symbol.for('IUpdateFraudReportUsecase'),
    IGetSuspendedUsersUsecase: Symbol.for('IGetSuspendedUsersUsecase'),
    IGetSuspensionUsersUsecase: Symbol.for('IGetSuspensionUsersUsecase'),
    FraudController: Symbol.for('FraudController'),
    FraudReportMapper: Symbol.for('FraudReportMapper'),
    UserSuspensionMapper: Symbol.for('UserSuspensionMapper'),
    IChatAgentService: Symbol.for('IChatAgentService'),
    ISendChatAgentMessageUsecase: Symbol.for('ISendChatAgentMessageUsecase'),
    IToolFactory: Symbol.for('IToolFactory'),
    IKnowledgeVectorStore: Symbol.for('IKnowledgeVectorStore'),
    IKnowledgeVectorDb: Symbol.for('IKnowledgeVectorDb'),
    ISubscriptionFeaturesRepository: Symbol.for(
        'ISubscriptionFeaturesRepository',
    ),
    SubscriptionFeaturesMapper: Symbol.for('SubscriptionFeaturesMapper'),
    AutoBidConfigMapper: Symbol.for('AutoBidConfigMapper'),
    IUpdateSubscriptionPlanUsecase: Symbol.for(
        'IUpdateSubscriptionPlanUsecase',
    ),
    ISubscriptionService: Symbol.for('ISubscriptionService'),
    IRazorpaySubscriptionWebhookHandlerUsecase: Symbol.for(
        'IRazorpayWebhookhandlerUsecase',
    ),
    IWalletService: Symbol.for('IWalletService'),
    ISubscriptionConfigService: Symbol.for('ISubscriptionConfigService'),
    ICacheService: Symbol.for('ICacheService'),
    IAuctionNumberGeneratingService: Symbol.for(
        'IAuctionNumberGeneratingService',
    ),
};
