export const TYPES = {
  ILogger: Symbol.for('ILogger'),
  IUserRepository: Symbol.for('IUserRepository'),
  IEmailService: Symbol.for('IEmailService'),
  IPasswordService: Symbol.for('IPasswordService'),
  IIdGeneratingService: Symbol.for('IIdGeneratingService'),
  IOtpService: Symbol.for('IOtpService'),
  IRegisterUseCase: Symbol.for('IRegisterUseCase'),
  EmailQueue: Symbol.for('EmailQueue'),
  PrismaClient: Symbol.for('PrismaClient'),
  AuthController: Symbol.for('AuthController'),
  Argon2Service: Symbol.for('Argon2Service'),
  IOtpRepository: Symbol.for('IOtpRepository'),
  ISendVerificationCodeUsecase: Symbol.for('ISendVerificationCodeUsecase'),
  IVerifyCredentialsUseCase: Symbol.for('IVerifyCredentialsUseCase'),
  ITokenGeneratorService: Symbol.for('ITokenGeneratorService'),
  ILoginUseCase: Symbol.for('ILoginUseCase'),
  IGetUserUsecase: Symbol.for('IGetUserUsecase'),
  IGoogleAuthUsecase: Symbol.for('IGoogleAuthUsecase'),
  ICompleteProfileUsecase: Symbol.for('ICompleteProfileUsecase'),
  IForgotPasswordUsecase: Symbol.for('IForgotPasswordUsecase'),
  IChangePasswordUsecase: Symbol.for('IChangePasswordUsecase'),
  AuthenticateMiddleware: Symbol.for('AuthenticateMiddleware'),
  AuthorizeMiddleware: Symbol.for('AuthorizeMiddleware'),
  UserController: Symbol.for('UserController'),
  ISendProfileChangePasswordOtpUsecase: Symbol.for(
    'ISendProfileChangePasswordOtpUsecase',
  ),
  IChangeProfilePasswordUsecase: Symbol.for('IChangeProfilePasswordUsecase'),
  IEditprofileSendOtpUsecase: Symbol.for('IEditprofileSendOtpUsecase'),
  IEditProfileUsecase: Symbol.for('IEditProfileUsecase'),
  ISendOtpUsecase: Symbol.for('ISendOtpUsecase'),
  OtpPolicyService: Symbol.for('OtpPolicyService'),
  IStorageService: Symbol.for('IStorageService'),
  S3Client: Symbol.for('S3Client'),
  IGenerateAvatarUploadUrlUsecase: Symbol.for(
    'IGenerateAvatarUploadUrlUsecase',
  ),
  IUpdateAvatarUrlUsecase: Symbol.for('IUpdateAvatarUrlUsecase'),
  IGetKycUploadUrlUsecase: Symbol.for('IGetKycUploadUrlUsecase'),
  KycController: Symbol.for('KycController'),
  IKycRepository: Symbol.for('IKycRepository'),
  IGetKycStatusUsecase: Symbol.for('IGetKycStatusUsecase'),
  IKycDocumentRepository: Symbol.for('IKycDocumentRepository'),
  IUpdateKycUsecase: Symbol.for('IUpdateKycUsecase'),
  ISubmitKycUsecase: Symbol.for('ISubmitKycUsecase'),
  IGetAllUsersUseCase: Symbol.for('IGetAllUsersUseCase'),
  AdminController: Symbol.for('AdminController'),
  AdminRoutes: Symbol.for('AdminRoutes'),
  IBlockUserUsecase: Symbol.for('IBlockUserUsecase'),
  IGetAdminUserUsecase: Symbol.for('IGetAdminUserUsecase'),
  IGetAllSellersUsecase: Symbol.for('IGetAllSellersUsecase'),
  IGetAdminSellerUsecase: Symbol.for('IGetAdminSellerUsecase'),
  IApproveSellerKycUsecase: Symbol.for('IApproveSellerKycUsecase'),
  IRejectSellerKycUsecase: Symbol.for('IRejectSellerKycUsecase'),
  IAuctionRepository: Symbol.for('IAuctionRepository'),
  ICreateAuctionUsecase: Symbol.for('ICreateAuctionUsecase'),
  IGetSellerAuctionsUsecase: Symbol.for('IGetSellerAuctionsUsecase'),
  IGetAuctionByIdUsecase: Symbol.for('IGetAuctionByIdUsecase'),
  IGenerateAuctionUploadUrlUsecase: Symbol.for(
    'IGenerateAuctionUploadUrlUsecase',
  ),
  IUpdateAuctionUsecase: Symbol.for('IUpdateAuctionUsecase'),
  IGetBrowseAuctionsUsecase: Symbol.for('IGetBrowseAuctionsUsecase'),
  IPublishAuctionUsecase: Symbol.for('IPublishAuctionUsecase'),
  IEndAuctionUsecase: Symbol.for('IEndAuctionUsecase'),
  AuctionController: Symbol.for('AuctionController'),
  AuctionRoutes: Symbol.for('AuctionRoutes'),
  IBidRepository: Symbol.for('IBidRepository'),
  IAuctionParticipantRepository: Symbol.for('IAuctionParticipantRepository'),
  IPlaceBidUsecase: Symbol.for('IPlaceBidUsecase'),
  IGetAuctionRoomUsecase: Symbol.for('IGetAuctionRoomUsecase'),
  IAuctionCategoryRepository: Symbol.for('IAuctionCategoryRepositoy'),
  IRequestAuctionCategoryUsecase: Symbol.for('IRequestAuctionCategoryUsecase'),
  ISlugGeneratorService: Symbol.for('ISlugGeneratorService'),
  IGetAllAuctionCategoriesUsecase: Symbol.for(
    'IGetAllAuctionCategoriesUsecase',
  ),
};
