export const USER_SUSPENSION_CONSTANTS = {
    TEMPORARY_SUSPENSION_DURATION: 7 * 24 * 60 * 60 * 1000,
    CRITICAL_FRAUD_LEVEL: 3,
    MEDIUM_FRAUD_LEVEL: 2,
    LOW_FRAUD_LEVEL: 1,
    SUSPENSION_THRESHOLD: 3,
};
